// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Order service

func NewOrderEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Order service

type OrderService interface {
	// 插入操作涉及到幂等性，需要生成全局唯一的订单ID
	InsertOrder(ctx context.Context, in *InserRequest, opts ...client.CallOption) (*InserResponse, error)
	GetOrder(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
	// 更新操作涉及到乐观锁做并发控制，所以需要传入版本号
	UpdateOrder(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) InsertOrder(ctx context.Context, in *InserRequest, opts ...client.CallOption) (*InserResponse, error) {
	req := c.c.NewRequest(c.name, "Order.InsertOrder", in)
	out := new(InserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) GetOrder(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.name, "Order.GetOrder", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) UpdateOrder(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "Order.UpdateOrder", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Order service

type OrderHandler interface {
	// 插入操作涉及到幂等性，需要生成全局唯一的订单ID
	InsertOrder(context.Context, *InserRequest, *InserResponse) error
	GetOrder(context.Context, *GetRequest, *GetResponse) error
	// 更新操作涉及到乐观锁做并发控制，所以需要传入版本号
	UpdateOrder(context.Context, *UpdateRequest, *UpdateResponse) error
}

func RegisterOrderHandler(s server.Server, hdlr OrderHandler, opts ...server.HandlerOption) error {
	type order interface {
		InsertOrder(ctx context.Context, in *InserRequest, out *InserResponse) error
		GetOrder(ctx context.Context, in *GetRequest, out *GetResponse) error
		UpdateOrder(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
	}
	type Order struct {
		order
	}
	h := &orderHandler{hdlr}
	return s.Handle(s.NewHandler(&Order{h}, opts...))
}

type orderHandler struct {
	OrderHandler
}

func (h *orderHandler) InsertOrder(ctx context.Context, in *InserRequest, out *InserResponse) error {
	return h.OrderHandler.InsertOrder(ctx, in, out)
}

func (h *orderHandler) GetOrder(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.OrderHandler.GetOrder(ctx, in, out)
}

func (h *orderHandler) UpdateOrder(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.OrderHandler.UpdateOrder(ctx, in, out)
}
